### PR TITLE
Fix typo in install instructions

### PR DESCRIPTION
**Pull request by dustinmichels**
Hi! It seems there was a typo in the install instructions: `xarray-leaflet`instead of `xarray_leaflet`.

### CODE REVIEW

**Comment by davidbrochart** [comment]
Thanks a lot! Maybe do the same for the `dynamic.ipynb` notebook?

**Comment by davidbrochart** [comment]
Thanks!

**Comment by davidbrochart** [comment]
BTW, you may have a git configuration issue (see https://github.community/t5/Support-Protips/Why-is-my-commit-associated-with-the-wrong-person/ba-p/6728).

**Comment by dustinmichels** [comment]
> BTW, you may have a git configuration issue (see https://github.community/t5/Support-Protips/Why-is-my-commit-associated-with-the-wrong-person/ba-p/6728).

Yeah, I noticed that... thanks for the link. Cool library!!

**Pull request merged**
